# nginx proxy address - http://172.17.0.1:8099

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  gatus:
    image: gatus/gatus:latest
    container_name: gatus-app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - gatus
    ports:
      - "8099:8099"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    volumes:
      - ./rootfs/config/gatus:/config
      - ./rootfs/data/gatus:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8099"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  gatus:
    external: false
